stages:
  - build
  - deploy

variables:
  # Utilise l'adresse officielle de ton registre GitLab
  IMAGE_TAG: $CI_REGISTRY_IMAGE:latest

# --- ÉTAPE 1 : CRÉATION ET ENVOI DE L'IMAGE SUR GITLAB ---
build_image:
  stage: build
  tags:
    - prod
  script:
    - echo "Connexion au registre GitLab..."
    # Les variables $CI_REGISTRY... sont automatiquement fournies par GitLab
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    
    - echo "Construction de l'image Docker..."
    - docker build -t $IMAGE_TAG .
    
    - echo "Envoi de l'image sur le registre GitLab..."
    - docker push $IMAGE_TAG
  only:
    - main

# --- ÉTAPE 2 : DÉPLOIEMENT DU CONTENEUR ---
deploy_production:
  stage: deploy
  tags:
    - prod
  script:
    - echo "Connexion au registre GitLab pour le déploiement..."
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    
    - echo "Téléchargement de la dernière image..."
    - docker pull $IMAGE_TAG
    
    - echo "Nettoyage de l'ancien conteneur..."
    - docker stop quizhub_app || true
    - docker rm quizhub_app || true
    
    - echo "Lancement du nouveau conteneur..."
    - docker run -d \
        --name quizhub_app \
        -p 4212:8080 \
        -v quizhub_database:/usr/src/quizhub/database \
        -v quizhub_sessions:/usr/src/quizhub/sessions \
        $IMAGE_TAG
    
    - docker image prune -f
    - echo "Déploiement terminé avec succès !"
  only:
    - main